### ISSUE TITLE
running into crush

### ISSUE THREAD

**Issue by Sibozhu** [Tom-Huang/carla_data_collection#3]
Dear @Tom-Huang ,

Thank you so much with your help on my previous problem, I just resolved the compiling issue, however, my Carla is keeping get crushed when I run your code:
```
python3 collect_albedo_depth_normal.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
enabling synchronous mode.
{'number_of_wheels': '4', 'sticky_control': 'true', 'object_type': '', 'color': '21,158,255', 'role_name': 'autopilot'}
{'number_of_wheels': '4', 'sticky_control': 'true', 'object_type': '', 'color': '255,0,0', 'role_name': 'autopilot'}
{'number_of_wheels': '4', 'sticky_control': 'true', 'object_type': '', 'color': '183,187,162', 'role_name': 'autopilot'}
{'number_of_wheels': '4', 'sticky_control': 'true', 'object_type': '', 'color': '183,187,162', 'role_name': 'autopilot'}
{'number_of_wheels': '4', 'sticky_control': 'true', 'object_type': '', 'color': '87,149,84', 'role_name': 'autopilot'}
{'number_of_wheels': '4', 'sticky_control': 'true', 'object_type': '', 'color': '18,185,251', 'role_name': 'autopilot'}
{'number_of_wheels': '4', 'sticky_control': 'true', 'object_type': '', 'color': '224,0,0', 'role_name': 'autopilot'}
{'number_of_wheels': '4', 'sticky_control': 'true', 'object_type': '', 'color': '243,243,243', 'role_name': 'autopilot'}
{'number_of_wheels': '4', 'sticky_control': 'true', 'object_type': '', 'color': '18,185,251', 'role_name': 'autopilot'}
{'number_of_wheels': '4', 'sticky_control': 'true', 'object_type': '', 'color': '255,0,0', 'role_name': 'autopilot'}
{'is_invincible': 'true', 'gender': 'male', 'speed': '0.0', 'age': 'adult', 'role_name': 'pedestrian'}
{'is_invincible': 'true', 'gender': 'female', 'speed': '0.0', 'age': 'child', 'role_name': 'pedestrian'}
{'is_invincible': 'true', 'gender': 'female', 'speed': '0.0', 'age': 'adult', 'role_name': 'pedestrian'}
{'is_invincible': 'true', 'gender': 'female', 'speed': '0.0', 'age': 'child', 'role_name': 'pedestrian'}
{'is_invincible': 'true', 'gender': 'female', 'speed': '0.0', 'age': 'child', 'role_name': 'pedestrian'}
{'is_invincible': 'true', 'gender': 'male', 'speed': '0.0', 'age': 'adult', 'role_name': 'pedestrian'}
{'is_invincible': 'true', 'gender': 'male', 'speed': '0.0', 'age': 'child', 'role_name': 'pedestrian'}
{'is_invincible': 'true', 'gender': 'male', 'speed': '0.0', 'age': 'child', 'role_name': 'pedestrian'}
{'is_invincible': 'true', 'gender': 'female', 'speed': '0.0', 'age': 'adult', 'role_name': 'pedestrian'}
{'is_invincible': 'true', 'gender': 'female', 'speed': '0.0', 'age': 'child', 'role_name': 'pedestrian'}
{'number_of_wheels': '4', 'sticky_control': 'true', 'object_type': '', 'color': '73,155,204', 'role_name': 'autopilot'}
{'lens_y_size': '0.08', 'lens_x_size': '0.08', 'lens_kcube': '0.0', 'lens_circle_multiplier': '0.0', 'lens_k': '-1.0', 'lens_circle_falloff': '5.0', 'fov': '120', 'image_size_y': '375', 'image_size_x': '1242', 'sensor_tick': '0.0', 'role_name': 'front'}
{'lens_y_size': '0.08', 'lens_x_size': '0.08', 'lens_kcube': '0.0', 'lens_circle_multiplier': '0.0', 'lens_k': '-1.0', 'lens_circle_falloff': '5.0', 'fov': '120', 'image_size_y': '375', 'image_size_x': '1242', 'sensor_tick': '0.0', 'role_name': 'front'}
{'chromatic_aberration_intensity': '0.0', 'white_clip': '0.04', 'toe': '0.55', 'shoulder': '0.26', 'blur_radius': '0.0', 'blur_amount': '1.0', 'blade_count': '5', 'min_fstop': '1.2', 'exposure_speed_up': '3.0', 'exposure_min_bright': '0.1', 'motion_blur_min_object_screen_size': '0.1', 'slope': '0.88', 'motion_blur_max_distortion': '0.35', 'motion_blur_intensity': '0.45', 'enable_postprocess_effects': 'true', 'temp': '6500.0', 'iso': '1200.0', 'tint': '0.0', 'calibration_constant': '16.0', 'shutter_speed': '60.0', 'focal_distance': '1000.0', 'exposure_compensation': '3.0', 'exposure_mode': 'manual', 'lens_y_size': '0.08', 'lens_x_size': '0.08', 'lens_kcube': '0.0', 'gamma': '2.2', 'lens_k': '-1.0', 'exposure_max_bright': '2.0', 'fstop': '1.4', 'lens_circle_multiplier': '0.0', 'lens_circle_falloff': '5.0', 'black_clip': '0.0', 'fov': '120', 'exposure_speed_down': '1.0', 'image_size_y': '375', 'image_size_x': '1242', 'sensor_tick': '0.0', 'chromatic_aberration_offset': '0.0', 'role_name': 'front'}

done.
Traceback (most recent call last):
  File "collect_albedo_depth_normal.py", line 450, in <module>
    main()
  File "collect_albedo_depth_normal.py", line 366, in main
    ts = world.wait_for_tick()
RuntimeError: time-out of 10000ms while waiting for the simulator, make sure the simulator is ready and connected to 127.0.0.1:2000
WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 298 (sensor.camera.depth) 
WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 299 (sensor.camera.semantic_segmentation) 
WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 300 (sensor.camera.rgb) 
[1]    13546 segmentation fault (core dumped)  python3 collect_albedo_depth_normal.py
```

When I run it, it first spawns NPCs, and after 3-4seconds of quietness, it gives me an error of core dumped. Do you have any experience/thoughts with this?

P.S: my desktop has 32G RAM (Pretty sure the crush has nothing to do with the size of memory), and GTX1080 GPU with 8GB memory

**Comment by Tom-Huang** [comment]
I haven't this error before. Did you check whether you connect the simulator to the port 127.0.0.1:2000? If so, I guess it could be that this code is apt for the Carla version 0.9.4 and you are using a newer version of Carla. Therefore the wait_for_tick method is changed. Please check the Carla documentation and see what if the appropriate way to run synchronous mode.

**Comment by Sibozhu** [comment]
Comment out line 367 does fix this problem, and seems it doesn't block the program from running.
https://github.com/Tom-Huang/carla_data_collection/blob/1e93a199c512c7797f4ae7f31e568f6e8f9b9673/collect_albedo_depth_normal.py#L367
